### ISSUE TITLE
Question : Is it possible the minSdkVersion to downgrade to 21 ?

### ISSUE THREAD

**Issue by polokoio456** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#13]
Hi, guys :
I need to use your WebRTC service on the sdk version 21 phone.

I found this file should need the sdk version at least 23, but I have no idea to no use this file.

"com.amazonaws:aws-android-sdk-mobile-client"

**Comment by zhiyua-git** [comment]
Hi @polokoio456 ,

The sample app is to demonstrate how Kinesis Video signaling work with websocket client and Android native WebRTC. The com.amazonaws:aws-android-sdk-mobile-client is just to provide an app base settings, if you use cognito client directly and with your own app and UI dependency, you can avoid the dependency on com.amazonaws:aws-android-sdk-mobile-client.

**Comment by polokoio456** [comment]
@zhiyua-git 
Thank you, I will try it.
