### ISSUE TITLE
Question: Can we send the stream of hardware camera connected to mobile device from webrtc?

### ISSUE THREAD

**Issue by JeetSA** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#21]
The hardware which is raspberry pi, is connected to a mobile device via wifi-network. The hardware is connected with a camera. I am able to fetch the stream from the hardware camera and show it in a Custom SurfaceView in Android App. The requirement is that I need to send the stream of that hardware to webrtc kinesis video streams from mobile application.

Can you please guide me with this?

Thanks.

**Comment by chehefen** [comment]
I think you can. Everything should be the save except the media source. You have to replace it with  the media source that fetch data from rpi.

**Comment by JeetSA** [comment]
Thank you for replying @chehefen 

How can I change the media source in android? It would be good if you can share any reference link or demo link for that.

**Comment by MushMal** [comment]
I am going to resolve this as the question is more suitable for Googles WebRTC specific forums. Alternatively, you could simply use embedded WebRTC where your software produces frames into the SDK
