### ISSUE TITLE
Echo handling

### ISSUE THREAD

**Issue by prechtelm** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#27]
Hi,
we experience extreme echoing during calls. How could we handle that problem?

we tried the following without any success:
`MediaConstraints mediaConstraints = new MediaConstraints();
mediaConstraints.mandatory.add(new MediaConstraints.KeyValuePair("googNoiseSuppression", "true"));
mediaConstraints.mandatory.add(new MediaConstraints.KeyValuePair("googEchoCancellation", "true"));`

and

`WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler(true);
WebRtcAudioUtils.setWebRtcBasedAutomaticGainControl(true);
WebRtcAudioUtils.setWebRtcBasedNoiseSuppressor(true);`

Any suggestions?

**Comment by MushMal** [comment]
KVS owns the signaling portion of the webrtc for Android. Perhaps, Googles webrtc forums might have a better answer for issues related to noice suppression.

**Comment by Caerbannog** [comment]
For your information, some other projects are calling `setWebRtcBasedAcousticEchoCanceler(false)` on specific phone models. This is fixes an echo on calls where the speaker is ON.
See: signalapp/Signal-Android#7635
