### ISSUE TITLE
Kinese Video Stream WebRTC Master Video Recording

### ISSUE THREAD

**Issue by mentordeveloper** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#29]
Hello,

Basically, we want to capture the WebRTC Master Video session and save them on AWS S3 Bucket for later use. can we do AWS Kinesis WebRTC Master Video Recording?

Kindly guide us the solution using AWS services?

**Comment by MushMal** [comment]
You could modify the underlying WebRTC code and tap into the frames to store them. That code is not owned by KVS. You might need to get some help from Google WebRTC forums.
