### ISSUE TITLE
Acces denied with a Cognito guest user

### ISSUE THREAD

**Issue by tantruongnhat** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#31]
Hi,
I am using this sample source.
I try to make this work with a Cognito guest user (I have enabled this in the identity pool and added kinesis to the IAM roles).
I skip the Login step. I gave the unauth role acces to kinesis in the iam overview.

![Screen Shot 2020-08-08 at 12 32 32 AM](https://user-images.githubusercontent.com/63728719/89672212-873e5480-d90e-11ea-9dbb-ffed32bea739.png)
![Screen Shot 2020-08-08 at 12 32 45 AM](https://user-images.githubusercontent.com/63728719/89672233-8c030880-d90e-11ea-9b69-88058f249800.png)
![Screen Shot 2020-08-08 at 12 33 07 AM](https://user-images.githubusercontent.com/63728719/89672241-902f2600-d90e-11ea-9130-7d59d113122b.png)

I still get the permission denied: AccessDeniedException

I also tried the issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/issues/8, but I can't find a way to implement CognitoCachingCredentialsProvider class.

How can I make it work?
Thanks

**Comment by hassanctech** [comment]
Currently we don't support access for Cognito guest users.  We are evaluating adding support for this in the future but do not have an ETA.

**Comment by MushMal** [comment]
Resolving this for now. We will update this as soon as we have more info
