### ISSUE TITLE
When I turn off the mobile from power button, the streaming is getting stopped after a minute.

### ISSUE THREAD

**Issue by JeetSA** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#32]
After starting the streaming from WebRTC when I switch off the mobile light by pressing the power button and keep it turned off for about a minute, the streaming is stopped from that device. The last frame is stuck in another mobile where I am getting the stream.

So is there any solution for the same? Can anyone please guide me on this?

Thanks

**Comment by MushMal** [comment]
You could modify the sample. The actual WebRTC implementation is based on Googles WebRTC. Perhaps their forums might have more info.

Resolving this for now

**Comment by MushMal** [comment]
*Modify the sample app to tear-down the webRTC stack on the app lifecycle changes
