### ISSUE TITLE
unstable Signaling client connection

### ISSUE THREAD

**Issue by jvasanthan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#34]
Hi Team,
The Signaling client connection is very unstable in the android sample provided. How to improve the signaling client connection stability. It is much better in js & c sdk.

**Comment by jvasanthan** [comment]
@disa6302 is this forum active? any inputs on the issue mentioned?

**Comment by MushMal** [comment]
This issue in not actionable. In order to get some traction on this, you might want to include the details of your scenario, the assets you are using and include the complete debug logs with the expected and observed behavior.

**Comment by jvasanthan** [comment]
@MushMal 
Test Setup:
Running Master in Device and Viewer in Android. Testing in Android 7.0 with minSdkVersion as 24

Following are the dependencies related to webrtc
    implementation 'org.webrtc:google-webrtc:1.0.28513'
    implementation 'org.glassfish.tyrus.bundles:tyrus-standalone-client:1.12'
    implementation 'org.awaitility:awaitility:3.0.0'
    implementation 'com.google.guava:guava:28.1-android'
    implementation 'org.apache.commons:commons-lang3:3.9'

Most of the time when signaling error occurs due to "Signaling client returned exception SSL handshake has failed". I have attached logs of working scenario and non-working scenario 

let me know if you need any more information 

[working_webrtc.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/files/5296687/working_webrtc.txt)
[not_working_webrtc.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/files/5296689/not_working_webrtc.txt)

Let me know if you need any more information.

**Comment by MushMal** [comment]
Looked at the logs and it does seem to be a networking issue. I am not familiar with the websocket client so perhaps there is a good way to enable a debug spew so need to look into.

Meanwhile can you ensure a good networking with low latency and see what’s special about your case. Try a different device with a different access point to narrow down. Sorry but there is not much in terms of KVS that I can suggest but to troubleshoot your networking

**Comment by jvasanthan** [comment]
@MushMal I checked the app in different networks they all have same issue. The issue, if I am right,  is related to Tyrus websocket client. Does it work stable in your test setup? Do you recommend any other websocket client? 
My beta release is stopped because of this issue, btw there is no issue with device or js app they work fine in the same network.

**Comment by MushMal** [comment]
Not sure - I don't have a setup that has issues but also don't have exhaustive tests. Some folks tried replacing Tyrus with OKhttp

**Comment by hassanctech** [comment]
We don't have any further info here.  Closing.
