### ISSUE TITLE
How can we add video effects

### ISSUE THREAD

**Issue by K12AZ** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#35]
Hello, I have set up this, and works perfectly. 

I wanted to add video effects and needs to transmit updated my video to peer connection. 

I think we need to process video frames, using open GL add effects and transmit to peer connection. 

Could you add this feature or could you able to guide me to develop this. 

TIA

**Comment by MushMal** [comment]
This would be a feature for the Google's WebRTC implementation that the sample is using.

Closing as it's not actionable right now.
