### ISSUE TITLE
GetClip API is not there in SDK for Android i.e.aws-android-sdk-kinesisvideo-archivedmedia

### ISSUE THREAD

**Issue by shishir87** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#37]
I am using aws-android-sdk-kinesisvideo-archivedmedia to show the video saved on Cloud. In my android app I want that user can download the video clip as well. To implement this download clip functionality I am looking for GetClip API which already present in SDK for java, but I want it in Android.

**Comment by MushMal** [comment]
@shishir87 this repository is about WebRTC signaling client implementation for Android and has nothing to do with KVS GetClip API.

This is the right repository for this issue: https://github.com/aws-amplify/aws-sdk-android/tree/main/aws-android-sdk-kinesisvideo-archivedmedia

NOTE: I don't think it's implemented yet in the AWS Mobile SDK yet.

**Comment by shishir87** [comment]
@MushMal Sorry for putting the issue here. Thanks for the reply
