### ISSUE TITLE
Question: How to change front to rear camera after the call is initialised?

### ISSUE THREAD

**Issue by JeetSA** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#38]
There is an option in the app to choose if the front camera or the rear camera. I want to implement a way to flip the camera after the call is started.

Can anyone please suggest to me how I can achieve this?

Thanks in advance.

**Comment by hassanctech** [comment]
We're not supporting this right now.  We would suggest just restarting the peer connection.

**Comment by hassanctech** [comment]
There is a `replaceTrack` method that can do this.  You can modify the sample to use this instead I think this should address your use case:  https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack

**Comment by stephanbordera** [comment]
Hi, I have upgraded to the latest iOS SDK via cocoa pod and there is no such method available, can you help ?

**Comment by saberzakhama** [comment]
Hello, I didn't found this method the replacetrack method on your Android sdk. Could you please upgrade your sdk with this feature. Thanks

**Comment by sharadrj** [comment]
replaceTrack should be in webrtc libraries on Andoird/iOS platforms. It is not part of the KVS SDK.
