### ISSUE TITLE
Question: How to disable TURN?

### ISSUE THREAD

**Issue by yuma-m** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#39]
I want to disable TURN in Android SDK. Will Android SDK use P2P only by commenting out the code block below?

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/df938e21d225a6183426d273f9cf059d7c73490f/src/main/java/com/amazonaws/kinesisvideo/demoapp/activity/WebRtcActivity.java#L366-L378

Environment
- Master: Android SDK
- Viewer: Android SDK
- Both devices are in the same local network and have to be connected via peer-to-peer definitely.

**Comment by MushMal** [comment]
Casually looking at it it should disable TURN as you are removing the ICE servers. Make sure you are not removing the STUN server which will be needed for the reflexive peer candidates.

**Comment by yuma-m** [comment]
Thank you @MushMal

I confirmed Android SDK will not send relay candidates by removing the code block above.
