### ISSUE TITLE
SIGSEGV(SEGV_MAPERR) Exception

### ISSUE THREAD

**Issue by KunNiu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#40]
Hi, I'm facing an exception.
Devce: Google PIXEL 2 XL
CPU:arm64-v8a
OS:Android 11,level 30
ROOM:google/taimen
LOG:
`

1     pc 000000001135de8c     /data/app/~~EGz8NpGwI7b-Ap7ZrlPtmA==/com.sktlab.android.veeko-kBY5eCZnJH24a_eYh4BxbA==/base.apk  (Java_org_webrtc_PeerConnection_nativeAddIceCandidate+96)
2    pc 0000000000012ed4    /apex/com.android.art/lib64/libart.so [arm64-v8a]
3    pc 0000000000009564    /apex/com.android.art/lib64/libart.so [arm64-v8a]
4     pc 000000000007f7e8    /apex/com.android.art/lib64/libart.so  (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int,  art::JValue*, char const*)+200) [arm64-v8a]
5     pc 00000000001f2040    /apex/com.android.art/lib64/libart.so  (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*,  art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376)  [arm64-v8a]
6     pc 00000000001e8228    /apex/com.android.art/lib64/libart.so (bool  art::interpreter::DoCall<false, false>(art::ArtMethod*,  art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned  short, art::JValue*)+912) [arm64-v8a]
7    pc 000000000055dd48    /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) [arm64-v8a]
8    pc 0000000000003914    /apex/com.android.art/lib64/libart.so [arm64-v8a]
9    pc 000000000002815c    [anon:dalvik-LinearAlloc]
10 java:
11 org.webrtc.PeerConnection.addIceCandidate(PeerConnection.java:879)
12 com.sktlab.android.veeko.webrtc.WebRtcActivity$2.onIceCandidate(WebRtcActivity.java:403)
13 com.sktlab.android.veeko.webrtc.signaling.SignalingListener$1.onMessage(SignalingListener.java:58)
14 com.sktlab.android.veeko.webrtc.signaling.SignalingListener$1.onMessage(SignalingListener.java:19)
15 org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:576)
16 org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:871)
17 org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:212)
18 org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:139)
19 org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:807)
20 org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:747)
21 org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:476)
22 org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114)
23 org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
24 org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:272)
25 org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
26 org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
27 org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
28 org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
29 org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
30 org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
31 org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
32 org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
33 org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
34 org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
35 org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
36 org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
37 org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
38 java.lang.Thread.run(Thread.java:923)

`

**Comment by MushMal** [comment]
I don't see any of the lines matching. What version are you using? Have you done any debugging to get more info? What's the scenario you are hitting? 

There is very little actionable in the issue. Please provide some debugging info, details, your scenario, versions, any changes, etc... Most importantly, a solid repro that we can look at.

**Comment by KunNiu** [comment]
@MushMal , this issue always happens when app come back from background during video call (go to background through home button before). I'm using version 2.16.5. I've compared with the build.gradle in your demo, the deference is I always use
`implementation ('org.glassfish.tyrus.bundles:tyrus-standalone-client:1.12'){
        exclude module : 'javax.inject'
    }`
and demo code will switch 1.12 & 1.15, according to min SDK version. I'm not sure if this caused the issue. 
I also can attach my WebRtcActivity class here, it have many differences with demo, so I'm not sure if there is something incorrect.
[WebRtcActivity.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/files/5572734/WebRtcActivity.txt)

**Comment by MushMal** [comment]
Not sure. We can't really debug custom applications. Can you reproduce this with the stock demo application?

**Comment by KunNiu** [comment]
After upgrade to org.glassfish.tyrus.bundles:tyrus-standalone-client:1.17, this issue disappeared, I think it may caused by lower tyrus version, so close this issue. Thanks @MushMal .
