### ISSUE TITLE
onResume & onPause demo request

### ISSUE THREAD

**Issue by KunNiu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#41]
Hi team, could you please add onResume & onPause demo in the WebRtcActivity? Will be very appreciate for this.
Thanks!

**Comment by MushMal** [comment]
Thanks for requesting an enhancement to the sample application. We will look into this in a priority order. Meanwhile, we always appreciate contributions.

**Comment by KunNiu** [comment]
@MushMal , Thanks for your reply,  is there a timeline for this? If it's a long term, maybe I will try my own solution.

**Comment by MushMal** [comment]
We won't be able to give any estimates or prioritization details as it depends on multiple factors. We would appreciate if you could contribute. This is an open source codebase.

**Comment by KunNiu** [comment]
@MushMal , well I'm very glade to contribute, but where could I find the API document? I only can find how to set up the demo code from web page and readme file. And I'm doing a feature that should support 1:M(one mater : many viewer) stream, is SDK support this feature? Thanks!

**Comment by MushMal** [comment]
There is some documentation on how to use the sample but the sample itself should have enough code comments. The underlying technology supports a single master multiple viewers. You can take a look at the native implementation of the master sample for example.

Resolving this issue for now
