### ISSUE TITLE
Unsupported operating system.

### ISSUE THREAD

**Issue by james04gr** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#42]
When i try to run the application i get the following error
AAPT2 aapt2-3.5.3-5435860-linux Daemon #0: AAPT2 is not supported on 32-bit Linux

I have a Lenovo laptop
Zorin OS 15.3
Intel Core i7-4710HQ @ 2.5 GHz
64-bit

I can't even run it on the emulator or my Samsung S9 device with Android 10

**Comment by disa6302** [comment]
@james04gr , 

We have not tested on Zorin OS. Can you be more specific on what you are trying to do?

**Comment by james04gr** [comment]
> @james04gr ,
> 
> We have not tested on Zorin OS. Can you be more specific on what you are trying to do?

I just want to run the demo application in my emulator or my physical device (Samsung S9 with Android 10)

**Comment by MushMal** [comment]
Stock Android should work just fine. Please follow the readme step-by-step and install the prerequisites and build. Please respond with more findings. We are not supporting Zorin OS.

**Comment by hassanctech** [comment]
Resolving due to staleness.  If there is still an issue please open with more details.
