### ISSUE TITLE
Minimum Memory / Storage / CPU requirements

### ISSUE THREAD

**Issue by guillaume-lecoz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#43]
Could you please let us know the requirements for using the WebRTC on a watch running Android?
Minimum Memory / Storage / CPU requirements ? 

To be exact we want use it on a device with QC2500 platform with 8909W running LAW 3.0 (Qualcomm version of Android).

**Comment by MushMal** [comment]
We haven't tested on this platform. The requirements (both static footprint and dynamic footprint) are vastly different for different platforms given the Android WebRTC implementation and dynamic media pipeline and networking requirements. I would recommend just running it and getting the data.

**Comment by MushMal** [comment]
Resolving
