### ISSUE TITLE
how Android App sends offers that support H264?

### ISSUE THREAD

**Issue by 3xLOGICAllenYang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#46]
We have a requirement to accept data from the camera side,
In the camera side, the supported codec type is H264, so android app need send H264 type to camera in the offer,
but From the Android log, the sent offer does not include the H264.
I want to know how Android App sends offers that support H264?

**Comment by disa6302** [comment]
@3xLOGICAllenYang , 

Apologies for the delay. I believe this question is being discussed in the [C SDK](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues). Closing this in favor of that.
