### ISSUE TITLE
Handle caching of ICE candidates

### ISSUE THREAD

**Issue by disa6302** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#47]
Because of out of order signaling message delivery, it is possible that the ICE candidates arrive before the answer in trickle ICE mode and the SDK does not track these ICE candidates. In the sample, we need to implement a caching logic to store any ICE candidates that are received before getting an answer to ensure we do not lose these while creating candidate pairs. The WebRTC C SDK handles this, but other SDKs do not.

Issue reference: #44

**Comment by unicornss** [comment]
[ wip ]  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/tree/test-pending-ice

**Comment by disa6302** [comment]
PR merged. Closing the issue.
