### ISSUE TITLE
Peer to Peer Streaming between Embedded SDK as master and Android device as viewer -  viewer can only see its' own camera media stream

### ISSUE THREAD

**Issue by ensean** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#49]
When using IPC as webrtc master, the media stream from the IPC camera can be viewed from the web console, but can not be viewed from the android app (viewer mode).
Any suggestion on how to determine the cause?

**Comment by disa6302** [comment]
@ensean , 

Can you check if the SDP exchange was successful? I suspect it is an issue with the H264 profile being chosen. You might have to add some code in the android SDK to ensure successful SDP exchange and proper encoding/decoding of the media. Check this [file](https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/HardwareVideoEncoderFactory.java) out. It has some helper functions that could be useful.

**Comment by ensean** [comment]
@disa6302 After several test, we found that this issue is related to device vendor. 

* Devices not working
  * Huawei Mate 30Pro
  * Huawei Nova 1s

* Device working
   *  Xiaomi

Is this related to https://github.com/react-native-webrtc/react-native-webrtc/issues/476#issuecomment-505456365

**Comment by disa6302** [comment]
@ensean , 

It is possible, but I cannot confirm since I have not worked with these devices.

**Comment by disa6302** [comment]
Closing since this is platform specific. Feel free to reach if you have any other questions.
