### ISSUE TITLE
after connect peer how to mute on or off??

### ISSUE THREAD

**Issue by Joseph-TSS** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#53]

**Comment by disa6302** [comment]
@Joseph-TSS , 

Question is not clear. Are you looking to mute local audio or received remote audio? 
If local audio, you can use `audioManager.setMicrophoneMute(boolean)` to do so.

**Comment by Joseph-TSS** [comment]
audioManager.setMicrophoneMute(boolean) its working for me and thanks a lot... again i need a favor from u (how to end the session and can i flip camera while live stream?)

**Comment by disa6302** [comment]
With the current sample, that is not possible. There is a UI button to select front or back facing camera. The best way would be to re-establish peer connection.

About ending session, `onDestroy()` handles it.

**Comment by disa6302** [comment]
Closing assuming question is answered
