### ISSUE TITLE
Proguard Rules

### ISSUE THREAD

**Issue by KunNiu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#55]
Hello engineers, please add the Proguard Rules, that's very important!

**Comment by disa6302** [comment]
@KunNiu ,

We already have a ticket tracking it (#26). Thanks for pointing out. We will work on it in priority basis. Closing as duplicate.

**Comment by KunNiu** [comment]
@disa6302 , yes, I know there is an exist ticket, but that has been created more than **9 months**, and I can't believe the proguard rules are so difficult to bring out. This really block app publish release version, could you please raise up the priority? Thanks!
