### ISSUE TITLE
Is it possible to use AWS Amplify without Cognito

### ISSUE THREAD

**Issue by southbaird** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#56]
Do not use Cognito

**Comment by shumai2112** [comment]
It is possible.

you can use StaticCredentialsProvider class instead of AWSCredentialsProvider class.

@Volatile
        private var credentialsProvider : StaticCredentialsProvider? = null

        @Synchronized
        fun getCredentialsProvider() :StaticCredentialsProvider? {
            if(credentialsProvider == null) {
                val credentials = BasicAWSCredentials(ACCESS_KEY, SECRET_KEY)
                credentialsProvider = StaticCredentialsProvider(credentials)
            }
            return credentialsProvider
        }

**Comment by southbaird** [comment]
> 有可能的。
> 
> 您可以使用 StaticCredentialsProvider 类而不是 AWSCredentialsProvider 类。
> 
> ```
>   @Volatile
>     private var credentialsProvider : StaticCredentialsProvider? = null
> 
>     @Synchronized
>     fun getCredentialsProvider() :StaticCredentialsProvider? {
>         if(credentialsProvider == null) {
>             val credentials = BasicAWSCredentials(ACCESS_KEY, SECRET_KEY)
>             credentialsProvider = StaticCredentialsProvider(credentials)
>         }
>         return credentialsProvider
>     }
> ```
I found that Congito and AWS Amplify have nothing to do with each other and both work。Thank you
