### ISSUE TITLE
Multiple viewer unable to connect simultaneously

### ISSUE THREAD

**Issue by matiasechaharria** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#58]
When a single master publishing Audio-video stream and 1 viewer is subscribing that stream and another viewer wants to subscribe then the whole system hangs and the publisher stops working

Scenario Steps:

Master starts publishing the stream on channel ‘A’
Viewer V1 connects and subscribe Channel A’ and can see and publish Audio-video
Viewer V2 connects and want to subscribe to the Channel ‘A’
Expected Result: Both viewer and the master simultaneously
Result Observed: When V2 connects then all Master viewers stuck

**Comment by disa6302** [comment]
@matiasechaharria ,

Are you trying to connect multiple viewers to a single android master? If that is the case, the android SDK does not support multi viewer configuration at the moment

**Comment by matiasechaharria** [comment]
yes is what i want to do.
I can see that ios - SDK has a multi viewer sample for uno master (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/tree/multiple-viewer-sample ) 
How i can implemet in android 1 Master multi viewer?
aws will implement multi viewer in android? 
can i run a more than one master in he same android device?

**Comment by disa6302** [comment]
@matiasechaharria , 

You can make the changes in the sample similar to iOS. We do plan to look into multi viewer for android, but we do not have a timeline for this yet. 
Also, multi master is not a possibility at this point.
