### ISSUE TITLE
how to banlance webrtc & kvs cloud storage

### ISSUE THREAD

**Issue by HiconKong** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#60]
recently i clone kvs demo and attach it with webrtc,but i found when used AndroidCameraMediaSource.setPreviewSurfaces(new Surface(SurfaceTextureHelper.getSurfaceTexture())), i got black screen    on my android device,but cloud html page can view video normally,how can i fix the abnormal on my android device.

In addition,how can i change mediaSource configuration after its start.

**Comment by disa6302** [comment]
If the video is not visible on the Android device, there must be something wrong with the way the API is being used and not related to KVS WebRTC at all. 

You can change it (the sample does not do that), but it might require SDP exchange again to have updated attributes to support the P2P communciation.
