### ISSUE TITLE
WebSocketClient  java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by mjkimloan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#61]
this problem in webrtcClient

        Endpoint endpoint = new Endpoint() {

            @Override
            public void onOpen(final Session session, final EndpointConfig endpointConfig) {
                Log.d(TAG, "Registering message handler");
                session.addMessageHandler(signalingListener.getMessageHandler());
            }

            @Override
            public void onClose(final Session session, final CloseReason closeReason) {
                super.onClose(session, closeReason);
                Log.d(TAG, "Session " + session.getRequestURI() + " closed with reason " +
                        closeReason.getReasonPhrase());
            }

            @Override
            public void onError(final Session session, final Throwable thr) {
                super.onError(session, thr);
                Log.w(TAG,"Session Error Caause // Message: " + thr.getCause() + "//" + thr.getMessage());
            }
        };

In onError, session is null and the reason for Throwable is Cannot cast java.lang.ClassCastException: java.lang.Boolean to java.lang.String. Is there a solution? 
also, Is there any effect on org.glassfish.tyrus.bundles:tyrus-standalone-client version?

**Comment by mjkimloan** [comment]
resolved only kotlin version change

**Comment by mjkimloan** [comment]
After changing the kotlin version it works fine.

**Comment by ronbarrera** [comment]
Hi, @mjkimloan I'm having the same issue, what Kotlin version are you using to solve this issue?

**Comment by mjkimloan** [comment]
@ronbarrera Hi !!  We are using version 1.4.32 and it has been confirmed that it does not work in later versions.

**Comment by ronbarrera** [comment]
@mjkimloan thanks. I'm using 1.4.32 and it works.

**Comment by mjkimloan** [comment]
@ronbarrera Thank You and it worked.
