### ISSUE TITLE
Project support

### ISSUE THREAD

**Issue by mfalconf** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#62]
At the company where I work we are interested in using Kinesis WebRTC to make video calls. The hardware of our cameras is hardware that runs Android 8. From what I understand this project is intended to be used on Android and its integration would not be a problem on our cameras. What worries me is the maintenance that this project has. Could you tell me what is the roadmap of it?

**Comment by disa6302** [comment]
@mfalconf ,

For any such questions, please reach out to kinesis-video-support@amazon.com.
