### ISSUE TITLE
Handle no message received at SignalingListener [question]

### ISSUE THREAD

**Issue by ronbarrera** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#65]
I was wondering if it is possible to get help. I have an embedded camera as the master, and I'm using my Android app as the viewer. However, how could I handle it when my camera is not connected and I launch the app? Looking at the SignalingListener, I can't tell whether I received an actual message or not.

**Comment by disa6302** [comment]
@ronbarrera , 

If the camera is not connected, the master would not receive the offer and hence the android app would not receive the answer. The best way to go about this would be to wait for an answer for a fixed amount of time and resend offer if the answer is not received. Closing now. Feel free to reach out if you have any more questions.
