### ISSUE TITLE
Acquire video from Signaling channels

### ISSUE THREAD

**Issue by Khoronus** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#66]
To the team.
Thank you for the project.

I was able to create a Signaling channel as specified in the demo, and I can see the result with "Kinesis Video Streams/Signaling Channels/Media playback".
Is it possible to read the video data by using a python code?
When I try to use the instruction "get_signaling_channel_endpoint", I get the following error message:
"botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetDataEndpoint operation: The requested stream is not found or not active."

FYI, the Signaling channel is properly described when I execute the function "describe_signaling_channel".

Thank you in advance.

**Comment by disa6302** [comment]
@Khoronus , 

We officially do not have a Python WebRTC SDK apart from the APIs, so not very sure how you have designed your application. Please follow the android sample closely to replicate in Python.
