### ISSUE TITLE
[Question] Video Playback (Signaling channels) - Python

### ISSUE THREAD

**Issue by Khoronus** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#67]
Is it possible to retrieve the video stream like realtime playback through WebRTC?

Similar to the question at:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues/11

If it is possible, can you give me some tips, advise, or information about how to implement in python?
I would like to retrieve the video sent from this SDK as master to a python viewer, like the Media Playback Viewer in the "Kinesis/Signaling Channels" 

![SignalingChannels-MediaPlaybackViewer](https://user-images.githubusercontent.com/9549910/122185522-1ff71680-cec8-11eb-81fa-7b012bf0e7b2.jpg)

**Comment by disa6302** [comment]
@Khoronus , 

Your viewer can receive frames from the master peer and to view the video, you will have to tie it with a GStreamer pipeline or callbacks programatically. Closing assuming answered. 

Your viewer could be anything, as long as it is tied to a proper media viewing tool.
