### ISSUE TITLE
App initial page

### ISSUE THREAD

**Issue by lhuijae** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#76]
**Brief**

When I build and run the app, it will be displayed as below.
And I can't do anything.
What's wrong?
![Screenshot_20220113-153618_AWSKinesisVideoWebRTCDemoApp](https://user-images.githubusercontent.com/13791042/149279171-2f599271-fba9-4a6b-8944-d178a06ca9b3.jpg)

**Comment by lhuijae** [comment]
I solved it.
Thanks.

**Comment by brandonregard** [comment]
Got the same here. Any chance you can share the fix? Thanks.

**Comment by brandonregard** [comment]
@lhuijae Got the same here. Any chance you can share the fix? Thanks.
