### ISSUE TITLE
Kinesis Data Analytics with WebRTC

### ISSUE THREAD

**Issue by ricamano** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#78]
Hey there, I am wondering if I can use Kinesis Data Analytics with a Live video stream with webrtc communication, such as detecting faces from the video stream using AWS. I can't seem to find an answer to this question anywhere else, so hopefully this is the right place and sorry if it isn't.

**Comment by sirknightj** [comment]
Hi,

Kinesis Video Streams offers a WebRTC ingestion feature which can allow you to send video over WebRTC to a Kinesis Video Stream. From there, you can use other AWS services such as [Amazon Rekognition](https://docs.aws.amazon.com/rekognition/latest/dg/faces.html) or [Amazon Sagemaker](https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html) to take the video from the stream and perform analysis on it. 

There's a blog post about it which you can read about [here](https://aws.amazon.com/blogs/machine-learning/easily-perform-facial-analysis-on-live-feeds-by-creating-a-serverless-video-analytics-environment-with-amazon-rekognition-video-and-amazon-kinesis-video-streams/).

To learn more about the WebRTC ingestion feature, check out [the documentation](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/webrtc-ingestion.html).

Hope this helps!
