### ISSUE TITLE
Get more detailed information of logged in user

### ISSUE THREAD

**Issue by ngupta1807** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#79]
Hi team , Thanks for the tutorial you have provided. 
But i have 1 issue coming . I want to know the logged user details like email id , username , phone number that they used while signup , Can you please help me in this that how can i get this information.

Thanks & Regards
Nisha

**Comment by sirknightj** [comment]
Hi Nisha,
Head over to [Cognito on the AWS Console](https://console.aws.amazon.com/cognito/). Make sure you're viewing the new version of the Amazon Cognito console (should be a blue banner at the top of the page). Click on the name of the user pool you created.
From there, scroll down and you should see a list of your users. If not, make sure the `Users` tab is selected. By default, usernames and emails are shown. If you want to see phone numbers, select the settings cog under the `Create user` button, change the switch next to Phone number, and click `Confirm`.

Hope this helps! See the [related article](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-manage-user-accounts.html) if you would like more information.
