### ISSUE TITLE
Could you please update Google's webrtc library to 1.0.32006?

### ISSUE THREAD

**Issue by masa-fujino** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#80]
As shown below, this SDK depends on Google's webrtc library.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/43236f56b438c112a6b4823e790baecb95ee61c8/build.gradle#L125

The version of this webrtc library is old (released July 2019).
Older versions do not work properly on the following HUAWEI devices.
> HUAWEI P30 lite, MAR-LX2J,  Android 10
> HUAWEI nova lite 2, Android 9

Could you please update Google's webrtc library to 1.0.32006?

**Comment by masa-fujino** [comment]
We tried updating Google's webrtc library to 1.0.32006 and it worked fine.
Our product also supports the devices listed above, and we are concerned about the impact of this issue.

**Comment by disa6302** [comment]
PR merged
