### ISSUE TITLE
the Cognito authentication for this sdk

### ISSUE THREAD

**Issue by bravepiper** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#83]
I'd like to know the authentication way for this sdk, besides Cognito, can app use access key id and session token to connect to kvs too?  if so, is there sample or document to guide how to do? 

Thanks

**Comment by bravepiper** [comment]
Any suggestion for this? thanks

**Comment by sirknightj** [comment]
Here are the credential providers available in the AWS SDK for Android: [JavaDoc](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/auth/AWSCredentialsProvider.html).

We only recommend using Cognito with mobile applications, which fetches and refreshes temporary AWS credentials for your account, and the SDK uses those Access Key, Secret Key, and Session Token for accessing the KVS APIs.

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/c5c37a4010d388411d02e771ae5649769a5ba69b/src/main/java/com/amazonaws/kinesisvideo/demoapp/activity/WebRtcActivity.java#L807-L812

There's an AWS article that you may want to check out [here](https://aws.amazon.com/articles/authenticating-users-of-aws-mobile-applications-with-a-token-vending-machine/) which explains vulnerabilities in your application if permanent non-rotating iam credentials were to be used.
