### ISSUE TITLE
Getting error in activating master or viewer mode

### ISSUE THREAD

**Issue by z4zzaman** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#85]
Hi dear,
 I just tried to build the master branch code and access the demo application, build was successful after adding a **gradle.properties**  file. 
But getting the following exception when trying to activate the master or Viewer mode of the demo application
 
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24, PID: 29618
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:295)
        at com.amazonaws.kinesisvideo.demoapp.activity.WebRtcActivity.onCreate(WebRtcActivity.java:439)

**Comment by sirknightj** [comment]
Hey @z4zzaman,

If you clone the repository, then open the project in Android Studio by choosing Open and selecting the build.gradle file, it should work out of the box. What issue are you encountering that needed a gradle.properties?

**Comment by sirknightj** [comment]
Closing due to no response. Please try running the sample as-is without any modifications (except to the ones mentioned [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#4-build-and-run-the-demo-application-using-android-studio)).
