### ISSUE TITLE
Audio Sample Rate update

### ISSUE THREAD

**Issue by sangavi-iderize** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#86]
HI Team, 
I have an condition to update the Sample rate from 48000 to 16000, Not able to update the codes, also not able to access the methods spend lotz of time on this, Need support to overcome this issue

**Comment by sirknightj** [comment]
Hey @sangavi-iderize, could you explain a bit more about what you mean by "Not able to update the codes, also not able to access the methods"? We need more information to be able to help out there.

To override both the input and output audio rate, create an [audio device module](https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/audio) and give it to the PeerConnectionFactory [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/blob/c5c37a4010d388411d02e771ae5649769a5ba69b/src/main/java/com/amazonaws/kinesisvideo/demoapp/activity/WebRtcActivity.java#L444-L448):
```
peerConnectionFactory =
                PeerConnectionFactory.builder()
                        .setVideoDecoderFactory(new DefaultVideoDecoderFactory(rootEglBase.getEglBaseContext()))
                        .setVideoEncoderFactory(new DefaultVideoEncoderFactory(rootEglBase.getEglBaseContext(), ENABLE_INTEL_VP8_ENCODER, ENABLE_H264_HIGH_PROFILE))
                        .setAudioDeviceModule(JavaAudioDeviceModule.builder(getApplicationContext())
                                .setSampleRate(16000)
                                .createAudioDeviceModule())
                        .createPeerConnectionFactory();
```

For more information on `setSampleRate`, its documentation is [here](https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/audio/JavaAudioDeviceModule.java#72).

**Comment by sangavi-iderize** [comment]
You are rally a saver for me, I'm trying for this for more than 2 days not able to find this piece of code, done loz and lotz of changes 

Also need some support on how to check buffering and how to do auto reconnect
