### ISSUE TITLE
How set the opus encoding for input audio?

### ISSUE THREAD

**Issue by SangKarthi94** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#87]
To send the local audio to the PeerConnection, we need to encode the microphone audio as ENCODING_OPUS. Currently, the audio encoding is set to PCM_16BIT by default, so we would require a callback mechanism to dynamically change the encoding attributes.

**Comment by niyatim23** [comment]
This can be achieved by SDP re-negotiation but you will experience a brief interruption during the process
